### PR TITLE
safely handle check for removal

### PR DESCRIPTION
**Pull request by efx**
Started testing #17 on our private repo and noticed one of our integration tests errored when running the rewrite. A safety check resolved it as needed.

### CODE REVIEW

**Comment by Turbo87** [comment]
can you add a test for this issue?

**Comment by efx** [comment]
sure thing

**Comment by efx** [comment]
I'll have to pick this up on Monday. Adding a test shows that the other issue I reported seems to be caused by how I define a `render` function in the `beforeEach` blocks. Seems easiest to relabel the custom function with an incrementing integer.

**Comment by efx** [comment]
I rebased with a consolidated approach here: https://github.com/Turbo87/ember-mocha-codemods/compare/master...efx:fix-14?expand=1. I'll try to finalize that sometime this week, but need to pause per other deadlines now. I got stuck correctly invoking the jscodeshift methods and when to do so within the rewrite flow.

**Pull request closed without merging**
